# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.CharField(default='123456', max_length=64),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
