# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_article_title_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/uploads', verbose_name='文章配图'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='head_img',
            field=models.ImageField(blank=True, height_field=150, null=True, upload_to='static/images/uploads', width_field=150),
        ),
    ]
