# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_auto_20170418_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, help_text='修改时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(blank=True, help_text='生成时间', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comm_date',
            field=models.DateTimeField(auto_now_add=True, help_text='评论时间'),
        ),
    ]
