# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_auto_20170418_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_friends_+', to='bbs.UserProfile'),
        ),
        migrations.AlterField(
            model_name='article',
            name='brief',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='article',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_img',
            field=models.ImageField(blank=True, null=True, upload_to='statics/images/uploads', verbose_name='文章配图'),
        ),
        migrations.AlterField(
            model_name='category',
            name='brief',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='板块名'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(help_text='所属文章', on_delete=django.db.models.deletion.CASCADE, to='bbs.Article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comm_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='head_img',
            field=models.ImageField(blank=True, height_field=150, null=True, upload_to='statics/images/uploads', width_field=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=models.TextField(blank=True, null=True, verbose_name='个人介绍'),
        ),
    ]
